import Image from "next/image";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";

const merchandise = [["GESS Polo", "/UNIFORMS/GESSPOLO.jpg", "A clean everyday layer, made for the field and campus."], ["GESS Windbreaker", "/UNIFORMS/WINDBREAKER.jpg", "A weather-ready outer layer for movement and shared identity."]] as const;

export default function MerchPage() {
  return <><SiteHeader /><main><section className="page-hero"><div className="relative z-10 mx-auto max-w-7xl"><p className="section-kicker">Uniform collection</p><h1 className="mt-4 max-w-3xl text-4xl font-bold sm:text-5xl">Wear the work. Carry the community.</h1><p className="mt-5 max-w-xl leading-7 text-emerald-50/80">The GESS uniform collection is designed around a shared presence, on campus and beyond.</p></div></section><section className="content-band"><div className="mx-auto max-w-7xl px-6 py-14 sm:py-20"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow-rule">Field-ready identity</p><h2 className="mt-3 text-2xl font-bold text-forest">Choose your layer.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Ask the team about current sizing, availability, and collection drops.</p></div><div className="grid gap-7 md:grid-cols-2">{merchandise.map(([name, src, description], index) => <article key={name} className="interactive-card group overflow-hidden"><div className="relative overflow-hidden bg-forest"><Image src={src} alt={name} width={1200} height={900} className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-105" priority={index === 0} /><span className="absolute left-5 top-5 rounded-full bg-forest/90 px-3 py-1 text-xs font-bold uppercase tracking-wider text-topo">Uniform {index + 1}</span></div><div className="p-6"><h2 className="text-2xl font-bold text-forest">{name}</h2><p className="mt-3 max-w-md leading-7 text-slate-600">{description}</p><Link href="/contacts#suggestions" className="mt-6 inline-block font-bold text-survey underline decoration-topo decoration-2 underline-offset-4 hover:text-forest">Ask about availability →</Link></div></article>)}</div></div></section></main></>;
}
